interface tooltipInfo {
  title: string;
  text: string;
  ready?: boolean;
  disabled?: boolean;
  tooltipDisabled?: boolean;
  textComponentName?: string; // custom component in case text is not enough
}

export const infoTooltipText: Record<string, tooltipInfo> = {
  "Energy-Facilities": {
    title: "Energy - Facilities",
    ready: true,
    text: "The Facilities module enables the user to calculate the emissions from facilities such as schools using either diesel, solar or national grid energy sources or a hybrid mix of these sources. <br/> The GHG Emission Calculator only considers Scope 1 and 2 emissions. The calculations are estimations. For solar in particular, it is assumed that the addition of solar panels will add zero emissions.",
  },
  "Energy-Cooking": {
    title: "Energy - Cooking",
    ready: true,
    text: "The Cooking module will enable the user to calculate the emissions from various forms of cookstoves including charcoal, firewood, briquettes, LPG, solar or grid connected and improved. Emissions calculations will also be updated if improved cooking appliances such as pressure cookers are used. Calculations will also include the emissions from charcoal production.",
  },
  "Energy-Lighting": {
    ready: true,
    disabled: false,
    title: "Energy - Lighting",
    text: "The Lighting module will enable the user to calculate the emissions from various forms of energy sources used to power lighting at homes and in the settlements. Energy sources considered include firewood, candle, kerosene, solar and the national grid. A hydrid electricity usage will be calculated based on the use of diesel gas, solar PV and the national grid.",
  },
  "WASH-Pumping": {
    ready: true,
    disabled: false,
    title: "WASH - Pumping",
    text: "The Pumping module will enable the user to calculate the emissions from pumping water or faecal sludge using either diesel, solar or national grid energy sources or a hybrid mix of these sources.",
  },
  "WASH-WaterSupply": {
    title: "Water supply",
    ready: true,
    text: "The Water Supply module calculates the emissions that are generated by either trucking water to and from a water source and a distribution point and/or by pumping from a borehole at the settlement. Either diesel or petrol trucks can be used in calculating emissions.",
  },
  // "Material-Shelter": {
  //   title: "Material - Shelter",
  //   text: "The Shelter and Site Materials module will enable the user to calculate the emissions from the production and transport of various shelter and site materials including cement, wood, bricks and metal. Emission factors come from the ICE or EcoInvent databases.",
  // },
  // "Material-CRI": {
  //   title: "Material - CRI",
  //   text: "The Core Relief Items (CRI) module will enable the user to calculate the emissions from the production and transport of various CRI materials including HDPE, LDPE, polyester, cotton and stainless steel. Emission factors come from the ICE or EcoInvent databases.",
  // },
  "WASH-DomesticSolidWaste": {
    ready: true,
    disabled: false,
    title: "Domestic solid waste",
    text: "The Domestic solid waste module will enable the user to calculate the emissions from the production and transport of various domestic solid waste materials including paper, plastic and biodegradable waste. Emission factors come from the ICE or EcoInvent databases.",
  },
  "Offset-TreePlanting": {
    title: "Offset - Tree planting",
    text: "The Offset module will enable the user to calculate the emissions saved from the planting of a variety of tree types. The module calculates based on the number of trees planted and the age of the tree to determine its carbon emission equivalent sequestration capacity.",
  },
  Results: {
    title: "Results",
    ready: true,
    tooltipDisabled: true,
    textComponentName: "ResultsTooltip",
    text: "The GHG Emission Calculator only considers Scope 1 and 2 emissions at this stage. The calculations are estimations. For solar in particular, it is assumed that the addition of solar panels will add zero emissions.<br/> Exceptionally, Scope 3 emissions associated with feedstock production and/or processing of charcoal, ethanol and vegetable oil are considered due to their high impact relative to the total emissions.",
  },
};
