[default]
CORS_ENABLED = false

S3_ENDPOINT_HOSTNAME = ""
S3_ENDPOINT_PROTOCOL = ""
S3_ACCESS_KEY_ID = ""
S3_SECRET_ACCESS_KEY = ""
S3_REGION = ""
S3_Bucket = ""
S3_Key = ""

AUTH_SERVER = "http://localhost:5984"

MAIL_USERNAME= ""
MAIL_PASSWORD= ""
MAIL_FROM = ""
MAIL_PORT = ""
MAIL_SERVER = ""
MAIL_FROM_NAME = ""

HOST_NAME = ""
COUCHDB_USER = ""
COUCHDB_PASSWORD = ""