FROM node:16-alpine as build-stage

WORKDIR /app

COPY package*.json ./
COPY .npmrc ./
COPY npm-shrinkwrap.json ./

RUN npm ci
# Set the PATH to include /app/node_modules/.bin
ENV PATH="/app/node_modules/.bin:${PATH}"

COPY public ./public
COPY src ./src
COPY *.js ./
COPY *.conf ./
COPY *.json ./

CMD ["npm", "run", "serve"]
