version: '3.9'
services:
  frontend:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-frontend:dev
    build: !reset null
    restart: always
  couchdb:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-couchdb:dev
    build: !reset null
    ports: !reset null
    restart: always
  couchdb-setup:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-couchdb-setup:dev
    build: !reset null
  data-setup:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-data-setup:dev
    build: !reset null
  s3_server:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-s3_server:dev
    build: !reset null
    ports: !reset null
    restart: always
  rest-api:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-rest-api:dev
    build: !reset null
    ports: !reset null
    restart: always
