version: "3.9"
services:
  develop-reverse-proxy:
    image: caddy:latest
    ports:
      - "8085:8085"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile