version: '3.9'
services:
  frontend:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-frontend:main
    build: !reset null
    restart: always
  couchdb:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-couchdb:main
    build: !reset null
    restart: always
  couchdb-setup:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-couchdb-setup:main
    build: !reset null
  s3_server:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-s3_server:main
    build: !reset null
    restart: always
  rest-api:
    image: ghcr.io/epfl-enac/unhcr-geneva-tech-hub-app-rest-api:main
    build: !reset null
    restart: always
