version: '3.8'
services:
  rest-api-develop:
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    ports:
      - "5051:5051"
    volumes:
      - ./rest-api/unhcr_tss/:/app/unhcr_tss/
    env_file:
      - ./rest-api/.env
    command: uvicorn unhcr_tss.main:app --host 0.0.0.0 --port 5051 --reload
