apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.fullname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend-pod
  template:
    metadata:
      labels:
        component: frontend-pod
    spec:
      # initContainers:
      #   # running couchdb-setup image
      #   - name: init-frontend-container
      #     image: {{ .Values.global.__common__.image.registry }}/{{ .Values.global.__common__.image.repository }}-couchdb-setup:{{ .Values.global.__common__.image.tag }}
      #     command: ['sh', '-c', 'echo "init container"']
      #   # running data-setup image
      #   - name: init-frontend-container-2
      #     image: {{ .Values.global.__common__.image.registry }}/{{ .Values.global.__common__.image.repository }}-data-setup:{{ .Values.global.__common__.image.tag }}
      #     command: ['sh', '-c', 'echo "init container 2"']
      containers:
        - name: frontend-container
          image: {{ .Values.global.__common__.image.registry }}/{{ .Values.global.__common__.image.repository }}-{{ .Values.frontend.fullname }}:{{ .Values.global.__common__.image.tag }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ include "tss.fullname" . }}-configmap-frontend
            - configMapRef:
                name: {{ include "tss.fullname" . }}-configmap
            - secretRef:
                name: {{ include "tss.fullname" . }}-secret-frontend