apiVersion: v1
kind: Pod
metadata:
  name: tss-backup-pod
spec:
  containers:
  - name: tss-backup
    image: cubocicloide/tss:backup.1
    command: ["sleep", "infinity"] # Mantiene il Pod attivo indefinitamente
    env:
      - name: AZURE_ACCOUNT_NAME
        valueFrom:
          secretKeyRef:
            name: tss-secret
            key: AZURE_ACCOUNT_NAME
      - name: AZURE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: tss-secret
            key: AZURE_ACCOUNT_KEY
      - name: AZURE_CONTAINER
        value: "backups"
      - name: COUCHDB_HOST
        valueFrom:
          configMapKeyRef:
            name: tss-configmap
            key: COUCHDB_HOST
      - name: COUCHDB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: tss-secret
            key: COUCHDB_PASSWORD
      - name: COUCHDB_USER
        valueFrom:
          secretKeyRef:
            name: tss-secret
            key: COUCHDB_USER
  restartPolicy: Always
