apiVersion: batch/v1
kind: Job
metadata:
  name: tss-data-restore-job
spec:
  template:
    spec:
      containers:
      - name: tss-data-restore
        image: cubocicloide/tss:jobs.10
        command: ["python", "main.py"]
        env:
          - name: AZURE_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: tss-secret
                key: AZURE_ACCOUNT_KEY
          - name: AZURE_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: tss-secret
                key: AZURE_ACCOUNT_NAME
          - name: AZURE_CONTAINER
            value: "backups"
          - name: BACKUP_NAME
            value: {BACKUP_NAME}
          - name: BASE_PATH
            value: "/home"
          - name: COUCH_URL
            valueFrom:
              secretKeyRef:
                name: tss-secret
                key: COUCH_URL
          - name: COUCHDB_HOST
            valueFrom:
              configMapKeyRef:
                name: tss-configmap
                key: COUCHDB_HOST
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tss-secret
                key: COUCHDB_PASSWORD
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: tss-secret
                key: COUCHDB_USER
          - name: DEST_DIR
            value: "/data"
          - name: JOB_NAME
            value: "1"
          - name: SOURCE_DIR
            value: "/data"
        volumeMounts:
          - name: database-storage
            mountPath: "/data"
      restartPolicy: OnFailure
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-storage-tss-couchdb-0
