apiVersion: apps/v1
kind: Deployment
metadata:
  name: tss-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tss-frontend
  template:
    metadata:
      labels:
        app: tss-frontend
    spec:
      containers:
      - name: tss-frontend
        image: vtripolitakis/tss-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: BASE_PATH
          valueFrom:
            configMapKeyRef:
              name: tss-config
              key: BASE_PATH
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: tss-config
              key: BASE_URL
        - name: BASE_URL_WITHOUT_SLASH
          valueFrom:
            configMapKeyRef:
              name: tss-config
              key: BASE_URL_WITHOUT_SLASH
        - name: VUE_APP_COUCHDB_URL
          valueFrom:
            configMapKeyRef:
              name: tss-config
              key: VUE_APP_COUCHDB_URL
        - name: VUE_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: tss-config
              key: VUE_APP_API_URL
        - name: VUE_APP_AZURE_CONTAINER_PREFIX
          valueFrom:
            configMapKeyRef:
              name: tss-config
              key: VUE_APP_AZURE_CONTAINER_PREFIX

---

apiVersion: v1
kind: Service
metadata:
  name: tss-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: tss-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
