apiVersion: v1
kind: Pod
metadata:
  name: tss-data-restore-pod
spec:
  containers:
  - name: tss-data-restore
    image: cubocicloide/tss:jobs.9
    command: ["sleep", "infinity"] # Mantiene il Pod attivo indefinitamente
    env:
      - name: AZURE_ACCOUNT_NAME
        valueFrom:
          secretKeyRef:
            name: tss-secret
            key: AZURE_ACCOUNT_NAME
      - name: AZURE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: tss-secret
            key: AZURE_ACCOUNT_KEY
      - name: AZURE_CONTAINER
        value: "backups"
      - name: BASE_PATH
        value: "/home"
      - name: BACKUP_NAME
        value: "1709290063738"
      - name: COUCHDB_HOST
        valueFrom:
          configMapKeyRef:
            name: tss-configmap
            key: COUCHDB_HOST
      - name: COUCHDB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: tss-secret
            key: COUCHDB_PASSWORD
      - name: COUCHDB_USER
        valueFrom:
          secretKeyRef:
            name: tss-secret
            key: COUCHDB_USER
      - name: DEST_DIR
        value: "/data"
      - name: JOB_NAME
        value: "3"
      - name: SOURCE_DIR
        value: "/data"
    volumeMounts:
      - name: database-storage
        mountPath: "/data"
  volumes:
    - name: database-storage
      persistentVolumeClaim:
        claimName: database-storage-tss-couchdb-0
  restartPolicy: Always
