install:
	cat materials.csv | python materials_csv_to_json.py > ../../frontend/src/assets/references/materials.json
	cat transports.csv | python transports_csv_to_json.py > ../../frontend/src/assets/references/transports.json
