FROM couchdb:3.3

# Define ARG for tenant ID
ARG AZURE_TENANT_ID

# Set the environment variable so that it's available to scripts during the build
ENV AZURE_TENANT_ID=${AZURE_TENANT_ID}

# Install required packages
RUN apt-get update && apt-get install -y python3 python3-pip wget
RUN pip3 install requests

# Copy script to generate local.ini
COPY generate_ini.py /opt/couchdb/etc/generate_ini.py

# Execute script to generate local.ini
RUN python3 /opt/couchdb/etc/generate_ini.py
