install:
	python data_converter_whole.py ../../frontend/src/assets/references/ ghg_default_value.csv
	python data_converter_whole.py ../../frontend/src/assets/references/ ghg_fnrb.csv
	python data_converter_whole.py ../../frontend/src/assets/references/ ghg_emission_factors.csv
	python data_converter_whole.py ../../frontend/src/assets/references/ ghg_grid_emission_factors.csv
	python data_converter_whole.py ../../frontend/src/assets/references/ solar_averaged.csv
	python data_converter_whole.py ../../frontend/src/assets/references/ unhcr_location.csv
	python data_converter_whole.py ../../frontend/src/assets/references/ ghg_ef_mixed_biowaste_list.csv
	python data_converter_whole.py ../../frontend/src/assets/references/ ghg_ef_mixed_non_biowaste_list.csv