name: docker

"on":
  push:
    branches:
      - dev

jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - if: ${{ github.ref_name == 'main' }}
        run: docker-compose build --pull
        env:
          DOCKER_TAG: latest
      - if: ${{ github.ref_name == 'dev' }}
        run: docker-compose build --pull
        env:
          DOCKER_TAG: beta
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker-compose push
